-- Initial manual setup required for each environment in target Snowflake account
-- Required before the deployment will work
-- The deployment uses <env>_DEVOPS_USER for acting on 
--  target environment in Snowflake account

-- variables --
SET TARGET_ENVIRONMENT = '<TARGET_ENV>'; -- DEV, TST

SET DEVOPS_USER = $TARGET_ENVIRONMENT || '_DEVOPS_USER';
SET DEVOPS_ROLE = 'FR_' || $TARGET_ENVIRONMENT || '_DEVOPS';
SET DEVOPS_WAREHOUSE = 'WH_' || $TARGET_ENVIRONMENT || '_DEVOPS';

USE ROLE ACCOUNTADMIN;

-- user and role --
CREATE USER IF NOT EXISTS IDENTIFIER($DEVOPS_USER)
    LOGIN_NAME = $DEVOPS_USER
    DISPLAY_NAME = $DEVOPS_USER
    RSA_PUBLIC_KEY = '<PUBLIC_KEY>'
    RSA_PUBLIC_KEY_2 = NULL
    TYPE = SERVICE;

CREATE ROLE IF NOT EXISTS IDENTIFIER($DEVOPS_ROLE);
GRANT ROLE ACCOUNTADMIN TO ROLE IDENTIFIER($DEVOPS_ROLE);
GRANT ROLE IDENTIFIER($DEVOPS_ROLE) TO USER IDENTIFIER($DEVOPS_USER);

-- DEVOPS warehouse --
CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($DEVOPS_WAREHOUSE)
WITH INITIALLY_SUSPENDED = TRUE
WAREHOUSE_SIZE = XSMALL
AUTO_SUSPEND = 60;

-- To verify what has been created
-- DESCRIBE USER IDENTIFIER($DEVOPS_USER);
-- SHOW GRANTS ON USER IDENTIFIER($DEVOPS_USER);
-- SHOW GRANTS ON ROLE IDENTIFIER($DEVOPS_ROLE);
-- DESCRIBE TABLE IDENTIFIER($HISTORY_TABLE);
