-- cleanup of resources created manually for deployment purposes
USE ROLE ACCOUNTADMIN;

-- should be repeated for each environment

DROP 
DROP WAREHOUSE IF EXISTS WH_TEST_DEVOPS;
DROP ROLE IF EXISTS FR_TEST_DEVOPS;
DROP USER IF EXISTS TEST_DEVOPS_USER;

-- and account level settings
DROP GIT REPOSITORY IF EXISTS ADMIN_DB.DEVOPS.DEVOPS_REPO;
DROP API INTEGRATION IF EXISTS GIT_API_INTEGRATION;
DROP SCHEMA IF EXISTS ADMIN_DB.DEVOPS;
DROP DATABASE IF EXISTS ADMIN_DB;
