-- database
CREATE OR ALTER DATABASE {{ ENV }}_RAW;
USE DATABASE {{ ENV }}_RAW;

-- AR_{ENV}_READ
GRANT USAGE ON DATABASE {{ ENV }}_RAW TO ROLE AR_{{ ENV }}_READ;

CREATE OR ALTER SCHEMA testing;

-- grants
-- AR_{ENV}_READ
GRANT USAGE ON SCHEMA testing TO ROLE AR_{{ ENV }}_READ;
GRANT SELECT ON FUTURE TABLES IN SCHEMA testing TO ROLE AR_{{ ENV }}_READ;
