-- DATA_ENG
CREATE OR ALTER WAREHOUSE WH_{{ ENV }}_DATA_ENG
WITH INITIALLY_SUSPENDED = TRUE
WAREHOUSE_SIZE = XSMALL
AUTO_SUSPEND = 60
;
USE WAREHOUSE WH_{{ ENV }}_DEVOPS;

GRANT USAGE ON WAREHOUSE WH_{{ ENV }}_DATA_ENG TO ROLE FR_{{ ENV }}_DATA_ENG;
