--- roles

CREATE OR REPLACE TEMPORARY TABLE ADMIN_DB.PUBLIC.EXPECTED_RESULTS AS SELECT * FROM
    VALUES
    ('AR_{{ ENV }}_READ', 'ROLE', 'USAGE', 'FR_{{ ENV }}_DATA_ENG')
    , ('WH_{{ ENV }}_DATA_ENG', 'WAREHOUSE', 'USAGE', 'FR_{{ ENV }}_DATA_ENG')
        AS T (NAME, GRANTED_ON, PRIVILEGE, GRANTEE_NAME);
CALL ADMIN_DB.DEVOPS.COMPARE_SHOW_TO_TABLE(
    'SHOW GRANTS TO ROLE FR_{{ ENV }}_DATA_ENG'
    , 'ADMIN_DB.PUBLIC.EXPECTED_RESULTS'
    , 'PRIVILEGE!=OWNERSHIP' -- filter USAGE only as DBT will have ownership of tables and schemas
);

--- databases
CREATE OR REPLACE TEMPORARY TABLE ADMIN_DB.PUBLIC.EXPECTED_RESULTS AS SELECT * FROM
    VALUES
    ('{{ ENV }}_RAW.TESTING', 'USAGE', 'ROLE', 'AR_{{ ENV }}_READ')
    , ('{{ ENV }}_RAW.TESTING', 'OWNERSHIP', 'ROLE', 'ACCOUNTADMIN')
        AS T (NAME, PRIVILEGE, GRANTED_TO, GRANTEE_NAME);
CALL ADMIN_DB.DEVOPS.COMPARE_SHOW_TO_TABLE(
    'SHOW GRANTS ON SCHEMA {{ ENV }}_RAW.TESTING'
    , 'ADMIN_DB.PUBLIC.EXPECTED_RESULTS'
);

CREATE OR REPLACE TEMPORARY TABLE ADMIN_DB.PUBLIC.EXPECTED_RESULTS AS SELECT * FROM
    VALUES
    ('{{ ENV }}_RAW.TESTING.<TABLE>', 'SELECT', 'TABLE', 'ROLE', 'AR_{{ ENV }}_READ')
        AS T (NAME, PRIVILEGE, GRANT_ON, GRANT_TO, GRANTEE_NAME);
CALL ADMIN_DB.DEVOPS.COMPARE_SHOW_TO_TABLE(
    'SHOW FUTURE GRANTS IN SCHEMA {{ ENV }}_RAW.TESTING'
    , 'ADMIN_DB.PUBLIC.EXPECTED_RESULTS'
);

--- warehouses
CREATE OR REPLACE TEMPORARY TABLE ADMIN_DB.PUBLIC.EXPECTED_RESULTS AS SELECT * FROM
    VALUES
    ('USAGE', 'WH_{{ ENV }}_DATA_ENG', 'FR_{{ ENV }}_DATA_ENG')
    , ('OWNERSHIP' ,'WH_{{ ENV }}_DATA_ENG', 'ACCOUNTADMIN')
        AS T (PRIVILEGE, NAME, GRANTEE_NAME);

CALL ADMIN_DB.DEVOPS.COMPARE_SHOW_TO_TABLE(
    'SHOW GRANTS ON WAREHOUSE WH_{{ ENV }}_DATA_ENG'
    , 'ADMIN_DB.PUBLIC.EXPECTED_RESULTS'
);