-- DATA_ENG
CREATE WAREHOUSE IF NOT EXISTS WH_{{ ENV }}_DATA_ENG
WITH INITIALLY_SUSPENDED = TRUE;
USE WAREHOUSE WH_{{ ENV }}_SCHEMACHANGE;

ALTER WAREHOUSE WH_{{ ENV }}_DATA_ENG
SET WAREHOUSE_SIZE = XSMALL
AUTO_SUSPEND = 60;

GRANT USAGE ON WAREHOUSE WH_{{ ENV }}_DATA_ENG TO ROLE FR_{{ ENV }}_DATA_ENG;
